/*
 * kernel/os/app.cpp - user programs (.app).
 *
 * A program is a relocatable ELF object: "ld -r" of its objects, the C library and libcrtos,
 * with no undefined symbols (it cannot call into the kernel except through SVC). It is
 * loaded at the bottom of a new arena and relocated there; the heap follows the image, the
 * main thread's stack and the startup block (arguments, environment) sit at the top:
 *
 *     | code | data | bss | heap ->            <- main stack | startup block |
 *
 * The arena is sized from the headers alone; the file is then read into the future heap
 * (kernel memory only if it does not fit), so a program needs no memory besides its arena.
 *
 * The section ".crtos_app" (struct crtos_app_info, generated by the build) gives the stack
 * and heap sizes. The entry point _start() gets the startup block in R0.
 *
 * Fast code: code executed from SDRAM runs at the speed of the instruction cache's misses
 * (about 200 cycles a 32-byte line), so a program may name its hottest functions (the build
 * renames their sections ".fast*", crtos_app FAST). They go to a block of on-chip memory -
 * ITCM, else OCRAM - that the process sees through one of its shared memory windows (user
 * read and execute); calls between the blocks go through veneers (elf.cpp). Without room
 * there the program is loaded as one block, as always.
 */
#define CRTOS_KERNEL 1
#include "kernel.h"
#include "elf.h"
#include <crtos/syscall.h>
#include <string.h>
#include "fsl_device_registers.h"

#define APP_STACK_DEFAULT   (16u * 1024u)
#define APP_HEAP_DEFAULT    (64u * 1024u)
#define APP_STACK_MAX       (1024u * 1024u)
#define APP_HEAP_MAX        (24u * 1024u * 1024u)   /* (cc1plus with the C++ library headers) */
#define APP_ARGS_MAX        4096u           /* bytes of argument and environment strings */
#define APP_FILE_MAX        (16 * 1024 * 1024)
#define APP_ARGV_MAX        64

struct app_syms {
    uint32_t exidx_start, exidx_end;
};

/* The only symbols a program may leave to the loader are the ones a linker script defines */
static uintptr_t app_resolve(const char *name, void *ctx)
{
    struct app_syms *s = (struct app_syms *)ctx;
    if (!strcmp(name, "__exidx_start"))
        return s->exidx_start;
    if (!strcmp(name, "__exidx_end"))
        return s->exidx_end;
    return 0;
}

static uint32_t strv_count(const char *const *v, uint32_t *bytes)
{
    uint32_t n = 0;
    if (v)
        for (; v[n] && n < APP_ARGV_MAX; n++)
            *bytes += (uint32_t)strlen(v[n]) + 1u;
    return n;
}

static void section_array(struct elf_ctx *c, const char *name, uint32_t *addr, uint32_t *count)
{
    uint32_t idx;
    const Elf32_Shdr *s = elf_section(c, name, &idx);
    *addr = s ? c->secaddr[idx] : 0;
    *count = s ? s->sh_size / 4u : 0;
}

/* Program name for ps: file name without directory and ".app" */
static void app_name(const char *path, char *out, size_t size)
{
    const char *b = strrchr(path, '/');
    b = b ? b + 1 : path;
    size_t n = strlen(b);
    if (n > 4 && !strcmp(b + n - 4, ".app"))
        n -= 4;
    if (n >= size)
        n = size - 1;
    memcpy(out, b, n);
    out[n] = 0;
}

/* Copy argv/envp and the startup block to the top of the arena; returns its offset */
static uint32_t build_startup(struct proc *p, const char *const *argv, const char *const *envp,
                              const struct crtos_startup *tmpl)
{
    uint32_t strbytes = 0;
    uint32_t argc = strv_count(argv, &strbytes);
    uint32_t envc = strv_count(envp, &strbytes);
    uint32_t block = (uint32_t)sizeof(struct crtos_startup) + (argc + envc + 2u) * 4u + ALIGN_UP(strbytes, 4u);
    uint32_t off = ALIGN_DOWN(p->arena_size - block, 8u);
    uint8_t *base = p->arena + off;
    struct crtos_startup *st = (struct crtos_startup *)base;
    char **uargv = (char **)(st + 1);
    char **uenvp = uargv + argc + 1;
    char *str = (char *)(uenvp + envc + 1);
    *st = *tmpl;
    st->argc = (int32_t)argc;
    st->argv = uargv;
    st->envp = uenvp;
    for (uint32_t i = 0; i < argc; i++) {
        size_t n = strlen(argv[i]) + 1;
        memcpy(str, argv[i], n);
        uargv[i] = str;
        str += n;
    }
    uargv[argc] = nullptr;
    for (uint32_t i = 0; i < envc; i++) {
        size_t n = strlen(envp[i]) + 1;
        memcpy(str, envp[i], n);
        uenvp[i] = str;
        str += n;
    }
    uenvp[envc] = nullptr;
    return off;
}

/* The program's ".fast" sections in on-chip memory, if it has some and there is room: splits
 * @c (the main block must fit where the one block would have gone, @isize and @ialign) and
 * returns the block with its size and MPU region; NULL: one block as usual */
static uint8_t *fast_block(struct elf_ctx *c, uint32_t isize, uint32_t ialign, uint32_t *bsize, uint32_t *rbar,
                           uint32_t *rasr)
{
    uint32_t msize, malign, fsize, falign;
    int r = elf_split_fast(c, &msize, &malign, &fsize, &falign);
    if (r) {
        if (r != -ENOENT)
            printk("W: %s: no fast code (%d)\n", c->who, r);
        return nullptr;
    }
    if (msize > isize || malign > ialign)
        printk("W: %s: no fast code (the image grows: %lu > %lu)\n", c->who, (unsigned long)msize,
               (unsigned long)isize);
    else {
        /* the fast code area at the top of ITCM */
        size_t size = 0;
        uint8_t *b = (uint8_t *)kmalloc_fastcode(fsize, &size);
        if (b && !mpu_encode_region(MPU_REGION_SHM0, (uintptr_t)b, size, MPU_ATTR_USER_RX, rbar, rasr)) {
            *bsize = size;
            return b;
        }
        kfree(b);
        /* else OCRAM: an MPU region must describe it, a power of two or a run of eighths of one */
        for (uint32_t l2 = 5; l2 <= 18; l2++) {
            uint32_t full = 1u << l2, sub = l2 >= 8 ? full / 8u : full;
            if (full < fsize)
                continue;
            uint32_t size = ALIGN_UP(fsize, sub);
            uint8_t *b = (uint8_t *)kmalloc_aligned(size, sub > falign ? sub : falign, KM_FAST | KM_EXEC | KM_ONCHIP);
            if (!b)
                continue;
            if (!mpu_encode_region(MPU_REGION_SHM0, (uintptr_t)b, size, MPU_ATTR_USER_RX, rbar, rasr)) {
                *bsize = size;
                return b;
            }
            kfree(b);
        }
        printk("W: %s: no room for %lu bytes of fast code\n", c->who, (unsigned long)fsize);
    }
    elf_unsplit(c);
    return nullptr;
}

static int read_at(struct file *f, uint32_t off, void *buf, uint32_t len)
{
    if (vfs_lseek(f, off, VFS_SEEK_SET) != (int64_t)off)
        return -EIO;
    for (uint32_t got = 0; got < len;) {
        int r = vfs_read(f, (uint8_t *)buf + got, len - got);
        if (r <= 0)
            return r < 0 ? r : -ENOEXEC;
        got += (uint32_t)r;
    }
    return 0;
}

/* What the arena depends on, from the headers alone (the file is read into the arena
 * afterwards): the image size and alignment, and the ".crtos_app" block (defaults if none) */
static int app_peek(struct file *f, uint32_t fsize, uint32_t *isize, uint32_t *ialign, struct crtos_app_info *info)
{
    Elf32_Ehdr eh;
    int r = read_at(f, 0, &eh, sizeof(eh));
    if (r)
        return r;
    if (memcmp(eh.e_ident, "\177ELF", 4) || eh.e_shentsize != sizeof(Elf32_Shdr) || !eh.e_shnum ||
        eh.e_shstrndx >= eh.e_shnum || eh.e_shoff > fsize ||
        (uint32_t)eh.e_shnum * sizeof(Elf32_Shdr) > fsize - eh.e_shoff)
        return -ENOEXEC;
    uint32_t shbytes = (uint32_t)eh.e_shnum * sizeof(Elf32_Shdr);
    Elf32_Shdr *sh = (Elf32_Shdr *)kmalloc(shbytes, KM_LARGE);
    char *names = nullptr;
    if (!sh)
        return -ENOMEM;
    r = read_at(f, eh.e_shoff, sh, shbytes);
    if (!r)
        r = elf_layout_sections(sh, eh.e_shnum, nullptr, isize, ialign);
    const Elf32_Shdr *ss = &sh[eh.e_shstrndx];
    if (!r && (!ss->sh_size || ss->sh_offset > fsize || ss->sh_size > fsize - ss->sh_offset))
        r = -ENOEXEC;
    if (!r) {
        names = (char *)kmalloc(ss->sh_size, KM_LARGE);
        r = names ? read_at(f, ss->sh_offset, names, ss->sh_size) : -ENOMEM;
        if (!r && names[ss->sh_size - 1])
            r = -ENOEXEC;
    }
    for (uint32_t i = 0; !r && i < eh.e_shnum; i++) {
        const Elf32_Shdr *s = &sh[i];
        if (s->sh_name >= ss->sh_size || strcmp(names + s->sh_name, ".crtos_app"))
            continue;
        if (s->sh_type != SHT_NOBITS && s->sh_size >= sizeof(*info) && s->sh_offset <= fsize - sizeof(*info))
            r = read_at(f, s->sh_offset, info, sizeof(*info));
        break;
    }
    kfree(names);
    kfree(sh);
    return r;
}

/* ---- programs that run in place (XIP) -----------------------------------------------------------
 *
 * A static position-independent executable (ELF ET_DYN, toolchain/crtos-xip.ld): a text
 * segment from address 0 (the ELF headers, code, constants, .rel.dyn) and a data segment from
 * XIP_DATA_BASE. The code reaches all data through the GOT, whose address every thread of the
 * process keeps in r9 (proc.cpp); no instruction needs relocating. So the text may stay where
 * the file is, when its file system can say where (file_ops.xip: /flash0) - then only the data
 * needs memory - or it is copied into the arena like any program:
 *
 *     | [text, if copied] | data | bss | heap ->            <- main stack | startup block |
 *
 * .rel.dyn holds R_ARM_RELATIVE entries for words of the data segment (the GOT, tables of
 * pointers, init/fini arrays); their value is an address in the text (below XIP_DATA_BASE) or
 * the data, which gets the segment's real place added. The file stays open as long as the
 * process lives, so a flash file system keeps it where it is (removing it frees it only then).
 */
#define XIP_DATA_BASE   0x10000000u
#define XIP_RELS_MAX    (1u << 20)

struct xip_image {
    uint32_t text_size;             /* file bytes of the text segment (from offset 0) */
    uint32_t data_vaddr, data_off, data_filesz, data_memsz, data_align;
    uint32_t entry;
    uint32_t got;                   /* vaddr of the GOT: r9 */
    uint32_t rel_off, rel_count;    /* .rel.dyn, inside the text */
    uint32_t pre, npre, ini, nini, fini, nfini;     /* vaddrs, counts */
    struct crtos_app_info info;
};

static int xip_peek(struct file *f, uint32_t fsize, const Elf32_Ehdr *eh, struct xip_image *x)
{
    if (eh->e_ident[4] != 1 || eh->e_ident[5] != 1 || eh->e_machine != EM_ARM ||
        eh->e_phentsize != sizeof(Elf32_Phdr) || !eh->e_phnum || eh->e_phnum > 16 ||
        eh->e_phoff > fsize || (uint32_t)eh->e_phnum * sizeof(Elf32_Phdr) > fsize - eh->e_phoff ||
        eh->e_shentsize != sizeof(Elf32_Shdr) || !eh->e_shnum || eh->e_shstrndx >= eh->e_shnum || eh->e_shoff > fsize ||
        (uint32_t)eh->e_shnum * sizeof(Elf32_Shdr) > fsize - eh->e_shoff)
        return -ENOEXEC;
    Elf32_Phdr ph[16];
    int r = read_at(f, eh->e_phoff, ph, (uint32_t)eh->e_phnum * sizeof(Elf32_Phdr));
    if (r)
        return r;
    bool text = false, data = false;
    for (uint32_t i = 0; i < eh->e_phnum; i++) {
        const Elf32_Phdr *p = &ph[i];
        if (p->p_type == PT_INTERP || p->p_type == PT_TLS)
            return -ENOEXEC; /* no dynamic linker, no thread-local storage */
        if (p->p_type != PT_LOAD)
            continue;
        if (!(p->p_flags & PF_W) && !text) {
            /* the text: where the file starts, as it is in the file */
            if (p->p_offset || p->p_vaddr || p->p_filesz != p->p_memsz || p->p_filesz > fsize ||
                p->p_filesz >= XIP_DATA_BASE)
                return -ENOEXEC;
            x->text_size = p->p_filesz;
            text = true;
        } else if ((p->p_flags & PF_W) && !(p->p_flags & PF_X) && !data) {
            if (p->p_vaddr < XIP_DATA_BASE || p->p_filesz > p->p_memsz || p->p_memsz > APP_HEAP_MAX ||
                p->p_offset > fsize || p->p_filesz > fsize - p->p_offset)
                return -ENOEXEC;
            x->data_vaddr = p->p_vaddr;
            x->data_off = p->p_offset;
            x->data_filesz = p->p_filesz;
            x->data_memsz = p->p_memsz;
            data = true;
        } else {
            return -ENOEXEC; /* only the two segments of crtos-xip.ld */
        }
    }
    if (!text || !data)
        return -ENOEXEC;
    if (!(eh->e_entry & 1u) || eh->e_entry >= x->text_size) {
        printk("E: no Thumb entry point in the text\n");
        return -ENOEXEC;
    }
    x->entry = eh->e_entry;

    uint32_t shbytes = (uint32_t)eh->e_shnum * sizeof(Elf32_Shdr);
    Elf32_Shdr *sh = (Elf32_Shdr *)kmalloc(shbytes, KM_LARGE);
    char *names = nullptr;
    if (!sh)
        return -ENOMEM;
    r = read_at(f, eh->e_shoff, sh, shbytes);
    const Elf32_Shdr *ss = &sh[eh->e_shstrndx];
    if (!r && (!ss->sh_size || ss->sh_offset > fsize || ss->sh_size > fsize - ss->sh_offset))
        r = -ENOEXEC;
    if (!r) {
        names = (char *)kmalloc(ss->sh_size, KM_LARGE);
        r = names ? read_at(f, ss->sh_offset, names, ss->sh_size) : -ENOMEM;
        if (!r && names[ss->sh_size - 1])
            r = -ENOEXEC;
    }
    x->data_align = 8;
    for (uint32_t i = 0; !r && i < eh->e_shnum; i++) {
        const Elf32_Shdr *s = &sh[i];
        if (s->sh_name >= ss->sh_size)
            continue;
        const char *n = names + s->sh_name;
        bool in_data = s->sh_addr >= x->data_vaddr && s->sh_addr - x->data_vaddr <= x->data_memsz &&
                       s->sh_size <= x->data_memsz - (s->sh_addr - x->data_vaddr);
        if ((s->sh_flags & SHF_ALLOC) && s->sh_addr >= XIP_DATA_BASE && s->sh_addralign > x->data_align)
            x->data_align = s->sh_addralign;
        if (!strcmp(n, ".crtos_app")) {
            if (s->sh_type != SHT_NOBITS && s->sh_size >= sizeof(x->info) && s->sh_offset <= fsize - sizeof(x->info))
                r = read_at(f, s->sh_offset, &x->info, sizeof(x->info));
        } else if (!strcmp(n, ".rel.dyn") && s->sh_type == SHT_REL) {
            if (s->sh_offset > x->text_size || s->sh_size > x->text_size - s->sh_offset ||
                s->sh_size / sizeof(Elf32_Rel) > XIP_RELS_MAX)
                r = -ENOEXEC;
            x->rel_off = s->sh_offset;
            x->rel_count = s->sh_size / sizeof(Elf32_Rel);
        } else if (!strcmp(n, ".got")) {
            x->got = in_data ? s->sh_addr : 0;
        } else if (!strcmp(n, ".preinit_array") || !strcmp(n, ".init_array") || !strcmp(n, ".fini_array")) {
            if (!in_data && s->sh_size)
                r = -ENOEXEC;
            uint32_t *addr = n[1] == 'p' ? &x->pre : n[1] == 'i' ? &x->ini : &x->fini;
            uint32_t *cnt = n[1] == 'p' ? &x->npre : n[1] == 'i' ? &x->nini : &x->nfini;
            *addr = s->sh_addr;
            *cnt = s->sh_size / 4u;
        }
    }
    kfree(names);
    kfree(sh);
    if (!r && !x->got) {
        printk("E: no GOT in the data segment\n");
        r = -ENOEXEC;
    }
    if (!r && x->data_align > 4096u)
        r = -E2BIG;
    return r;
}

/* the R_ARM_RELATIVE relocations: words of the data segment, their value moved to where the
 * text (@text) and the data (@data) really are */
static int xip_relocate(const struct xip_image *x, const uint8_t *text, uint8_t *data, const char *path)
{
    const Elf32_Rel *rel = (const Elf32_Rel *)(text + x->rel_off);
    for (uint32_t i = 0; i < x->rel_count; i++) {
        uint32_t type = rel[i].r_info & 0xFFu, off = rel[i].r_offset;
        if (type == 0) /* R_ARM_NONE */
            continue;
        if (type != R_ARM_RELATIVE || (rel[i].r_info >> 8)) {
            printk("E: %s: dynamic relocation type %lu (only R_ARM_RELATIVE: link with crtos-xip.ld)\n", path,
                   (unsigned long)type);
            return -ENOEXEC;
        }
        if (off < x->data_vaddr || off - x->data_vaddr > x->data_memsz - 4u || (off & 3u)) {
            printk("E: %s: relocation at %08lx outside the data\n", path, (unsigned long)off);
            return -ENOEXEC;
        }
        uint32_t *w = (uint32_t *)(data + (off - x->data_vaddr));
        uint32_t v = *w;
        if (v < x->text_size)
            *w = (uint32_t)(uintptr_t)text + v;
        else if (v >= x->data_vaddr && v - x->data_vaddr <= x->data_memsz)
            *w = (uint32_t)(uintptr_t)data + (v - x->data_vaddr);
        else {
            printk("E: %s: relocation at %08lx points to %08lx, outside the program\n", path, (unsigned long)off,
                   (unsigned long)v);
            return -ENOEXEC;
        }
    }
    return 0;
}

static struct proc *app_spawn_xip(struct proc *parent, const char *path, struct file *f, uint32_t fsize,
                                  const Elf32_Ehdr *eh, const char *const *argv, const char *const *envp,
                                  struct file *const stdio[3], uint32_t caps, int prio, int *err)
{
    struct proc *p = nullptr;
    struct xip_image x;
    memset(&x, 0, sizeof(x));
    x.info = { CRTOS_APP_MAGIC, CRTOS_APP_ABI, APP_STACK_DEFAULT, APP_HEAP_DEFAULT, 0 };
    int r = xip_peek(f, fsize, eh, &x);
    uintptr_t in_place = 0;
    uint32_t in_place_size = 0;
    if (!r && (x.info.magic != CRTOS_APP_MAGIC || x.info.abi != CRTOS_APP_ABI)) {
        printk("E: %s: program ABI %lu, kernel %lu\n", path, (unsigned long)x.info.abi, (unsigned long)CRTOS_APP_ABI);
        r = -ENOEXEC;
    }
    uint32_t stack = x.info.stack_size ? ALIGN_UP(x.info.stack_size, 32u) : APP_STACK_DEFAULT;
    uint32_t heap = x.info.heap_size ? ALIGN_UP(x.info.heap_size, 32u) : APP_HEAP_DEFAULT;
    if (!r && (stack > APP_STACK_MAX || heap > APP_HEAP_MAX))
        r = -E2BIG;
    uint32_t argbytes = 0;
    uint32_t nargs = strv_count(argv, &argbytes) + strv_count(envp, &argbytes);
    if (!r && argbytes > APP_ARGS_MAX)
        r = -E2BIG;
    /* the code in place, if its file system can: then only the data needs the arena */
    if (r || vfs_xip(f, &in_place, &in_place_size) || in_place_size < x.text_size || (in_place & 31u))
        in_place = 0; /* (the text runs at the file's place: aligned at least as the link assumed) */
    uint32_t text_room = in_place ? 0 : ALIGN_UP(x.text_size, 32u);
    uint32_t data_off = ALIGN_UP(text_room, x.data_align);
    uint32_t image = data_off + x.data_memsz;
    uint32_t top = stack + CONFIG_STACK_GUARD * 2u + (uint32_t)sizeof(struct crtos_startup) + (nargs + 2u) * 4u +
                   ALIGN_UP(argbytes, 4u);
    if (!r && !in_place && x.text_size > APP_FILE_MAX)
        r = -EFBIG; /* too big to copy: only in place */
    if (!r) {
        char name[16];
        app_name(path, name, sizeof(name));
        p = proc_create(name, ALIGN_UP(image, 8u) + heap + top, parent);
        if (!p)
            r = -ENOMEM;
    }
    uint8_t *text = nullptr, *data = nullptr;
    if (!r) {
        text = in_place ? (uint8_t *)in_place : p->arena;
        data = p->arena + data_off;
        if (!in_place)
            r = read_at(f, 0, p->arena, x.text_size);
    }
    if (!r)
        r = read_at(f, x.data_off, data, x.data_filesz); /* (the rest, bss, is zero: a new arena is) */
    if (!r)
        r = xip_relocate(&x, text, data, path);
    if (!r) {
        struct crtos_startup tmpl;
        memset(&tmpl, 0, sizeof(tmpl));
        tmpl.magic = CRTOS_STARTUP_MAGIC;
        uint32_t npre = x.npre, nini = x.nini;
        if (npre && nini && x.pre + npre * 4u != x.ini)
            npre = 0; /* one list only if adjacent (the linker script puts them so) */
        uint32_t first = npre ? x.pre : x.ini;
        tmpl.init_array = (void (**)(void))(uintptr_t)(first ? (uintptr_t)data + (first - x.data_vaddr) : 0);
        tmpl.init_count = npre + nini;
        tmpl.fini_array = (void (**)(void))(uintptr_t)(x.nfini ? (uintptr_t)data + (x.fini - x.data_vaddr) : 0);
        tmpl.fini_count = x.nfini;
        tmpl.arena = p->arena;
        tmpl.arena_size = p->arena_size;
        tmpl.pid = p->pid;
        if (!in_place)
            SCB_CleanDCache_by_Addr(p->arena, (int32_t)ALIGN_UP(x.text_size, 32u));
        SCB_InvalidateICache();
        p->sb = (uint32_t)(uintptr_t)data + (x.got - x.data_vaddr);
        p->text = (uint32_t)(uintptr_t)text;
        p->brk = p->heap_start = ALIGN_UP(image, 8u);
        uint32_t st_off = build_startup(p, argv, envp, &tmpl);
        p->stack_floor = st_off;
        p->caps = caps;
        for (int i = 0; i < 3; i++) {
            if (stdio && stdio[i]) {
                vfs_file_get(stdio[i]);
                handle_install_at(p, i, H_FILE, 0, stdio[i]);
            }
        }
        if (in_place) {
            p->text_size = x.text_size;
            p->xip_file = f; /* keeps the code where it is while the process lives */
            f = nullptr;
            printk("%s: code in place at %08lx (%lu KB), data %lu KB\n", p->name, (unsigned long)p->text,
                   (unsigned long)(x.text_size / 1024u), (unsigned long)(x.data_memsz / 1024u));
        }
        if (!proc_thread_create(p, (uint32_t)(uintptr_t)text + x.entry, (uint32_t)(uintptr_t)(p->arena + st_off),
                                stack, prio))
            r = -ENOMEM;
    }
    if (f)
        vfs_close(f);
    if (r && p) {
        proc_detach(p);
        proc_kill(p, r); /* never ran: releases the arena (and the file) */
        proc_put(p);
        p = nullptr;
    }
    if (err)
        *err = r;
    return p;
}

struct proc *app_spawn(struct proc *parent, const char *path, const char *const *argv, const char *const *envp,
                       struct file *const stdio[3], uint32_t caps, int prio, int *err)
{
    struct file *f = nullptr;
    uint8_t *file = nullptr, *fast = nullptr;
    uint32_t fast_size = 0, fast_rbar = 0, fast_rasr = 0;
    bool file_in_arena = false;
    uint32_t fsize = 0;
    struct proc *p = nullptr;
    struct elf_ctx c;
    memset(&c, 0, sizeof(c));
    int r = vfs_open(path, VFS_O_RDONLY, &f);
    if (r)
        goto out;
    {
        struct vfs_stat st;
        r = vfs_fstat(f, &st);
        if (r)
            goto out;
        /* a program that runs in place (ET_DYN) has a way of its own */
        Elf32_Ehdr eh;
        if (st.size > (int64_t)sizeof(eh) && st.size <= 0x7FFFFFFF && !read_at(f, 0, &eh, sizeof(eh)) &&
            !memcmp(eh.e_ident, "\177ELF", 4) && eh.e_type == ET_DYN) {
            struct proc *xp = app_spawn_xip(parent, path, f, (uint32_t)st.size, &eh, argv, envp, stdio, caps, prio, err);
            return xp; /* (it closed or kept the file) */
        }
        if (st.size <= 0 || st.size > APP_FILE_MAX) {
            r = st.size > 0 ? -EFBIG : -ENOEXEC;
            goto out;
        }
        fsize = (uint32_t)st.size;

        uint32_t isize, ialign;
        struct crtos_app_info info = { CRTOS_APP_MAGIC, CRTOS_APP_ABI, APP_STACK_DEFAULT, APP_HEAP_DEFAULT, 0 };
        r = app_peek(f, fsize, &isize, &ialign, &info);
        if (r)
            goto out;
        if (info.magic != CRTOS_APP_MAGIC || info.abi != CRTOS_APP_ABI) {
            printk("E: %s: program ABI %lu, kernel %lu\n", path, (unsigned long)info.abi,
                   (unsigned long)CRTOS_APP_ABI);
            r = -ENOEXEC;
            goto out;
        }
        uint32_t stack = info.stack_size ? ALIGN_UP(info.stack_size, 32u) : APP_STACK_DEFAULT;
        uint32_t heap = info.heap_size ? ALIGN_UP(info.heap_size, 32u) : APP_HEAP_DEFAULT;
        if (stack > APP_STACK_MAX || heap > APP_HEAP_MAX || ialign > 4096u) {
            r = -E2BIG;
            goto out;
        }
        uint32_t argbytes = 0;
        uint32_t nargs = strv_count(argv, &argbytes) + strv_count(envp, &argbytes);
        if (argbytes > APP_ARGS_MAX) {
            r = -E2BIG;
            goto out;
        }
        uint32_t top = stack + CONFIG_STACK_GUARD * 2u + (uint32_t)sizeof(struct crtos_startup) +
                       (nargs + 2u) * 4u + ALIGN_UP(argbytes, 4u);
        uint32_t need = ALIGN_UP(isize, 8u) + heap + top;

        char name[16];
        app_name(path, name, sizeof(name));
        p = proc_create(name, need, parent);
        if (!p) {
            r = -ENOMEM;
            goto out;
        }

        /* The file is read to where the heap will be (it starts out unused, and the file is
         * not needed once the image is placed and relocated), or into kernel memory if it
         * does not fit there */
        uint32_t spare = ALIGN_UP(isize, 32u);
        if (spare <= p->arena_size - top && fsize <= p->arena_size - top - spare) {
            file = p->arena + spare;
            file_in_arena = true;
        } else {
            file = (uint8_t *)kmalloc_aligned(fsize, 32, KM_LARGE);
            if (!file) {
                r = -ENOMEM;
                goto out;
            }
        }
        r = read_at(f, 0, file, fsize);
        vfs_close(f);
        f = nullptr;
        if (r)
            goto out;
        c.file = file;
        c.size = fsize;
        c.who = path;
        uint32_t isize2, ialign2;
        r = elf_check(&c);
        if (!r)
            fast = fast_block(&c, isize, ialign, &fast_size, &fast_rbar, &fast_rasr);
        for (;;) {
            if (!fast) {
                r = r ? r : elf_layout(&c, &isize2, &ialign2);
                if (!r && (isize2 != isize || ialign2 != ialign))
                    r = -ENOEXEC; /* changed while it was read */
                if (r)
                    goto out;
                elf_place(&c, p->arena);
            } else {
                elf_place_split(&c, p->arena, fast);
            }
            struct app_syms syms = { 0, 0 };
            uint32_t idx;
            const Elf32_Shdr *ex = elf_section(&c, ".ARM.exidx", &idx);
            if (ex) {
                syms.exidx_start = c.secaddr[idx];
                syms.exidx_end = c.secaddr[idx] + ex->sh_size;
            }
            r = elf_symbols(&c, app_resolve, &syms);
            if (!r)
                r = elf_relocate(&c);
            if (!r || !fast)
                break;
            /* the split image did not work out: as one block */
            printk("W: %s: no fast code (%d)\n", path, r);
            kfree(fast);
            fast = nullptr;
            r = 0;
            elf_unsplit(&c);
            elf_forget_symbols(&c);
        }
        if (r)
            goto out;
        uint32_t entry = elf_symbol(&c, "_start");
        if (!(entry & 1u)) {
            printk("E: %s: no Thumb entry point _start\n", path);
            r = -ENOEXEC;
            goto out;
        }

        struct crtos_startup tmpl;
        memset(&tmpl, 0, sizeof(tmpl));
        tmpl.magic = CRTOS_STARTUP_MAGIC;
        uint32_t pre, npre, ini, nini, fini, nfini;
        section_array(&c, ".preinit_array", &pre, &npre);
        section_array(&c, ".init_array", &ini, &nini);
        section_array(&c, ".fini_array", &fini, &nfini);
        if (npre && nini) {
            /* the image places sections by kind, not name: make one list only if adjacent */
            if (pre + npre * 4u != ini)
                npre = 0;
        }
        tmpl.init_array = (void (**)(void))(uintptr_t)(npre ? pre : ini);
        tmpl.init_count = npre + nini;
        tmpl.fini_array = (void (**)(void))(uintptr_t)fini;
        tmpl.fini_count = nfini;
        if (file_in_arena) /* done with the file: the heap starts out zeroed, as always */
            memset(file, 0, fsize);
        tmpl.arena = p->arena;
        tmpl.arena_size = p->arena_size;
        tmpl.pid = p->pid;

        SCB_CleanDCache_by_Addr(p->arena, (int32_t)ALIGN_UP(isize, 32u));
        if (fast) {
            SCB_CleanDCache_by_Addr(fast, (int32_t)fast_size); /* (OCRAM; ITCM is not cached) */
            p->fastcode = fast;
            p->fastcode_size = fast_size;
            p->win[0].shm = nullptr;
            p->win[0].rbar = fast_rbar;
            p->win[0].rasr = fast_rasr;
            fast = nullptr;
            printk("%s: %lu KB of fast code at %p\n", p->name, (unsigned long)(p->fastcode_size / 1024u),
                   (void *)p->fastcode);
        }
        SCB_InvalidateICache();
        p->brk = p->heap_start = ALIGN_UP(isize, 8u);

        uint32_t st_off = build_startup(p, argv, envp, &tmpl);
        p->stack_floor = st_off;
        p->caps = caps;
        for (int i = 0; i < 3; i++) {
            if (stdio && stdio[i]) {
                vfs_file_get(stdio[i]);
                handle_install_at(p, i, H_FILE, 0, stdio[i]);
            }
        }
        if (!proc_thread_create(p, entry, (uint32_t)(uintptr_t)(p->arena + st_off), stack, prio)) {
            r = -ENOMEM;
            goto out;
        }
    }

out:
    elf_release(&c);
    kfree(fast); /* (not given to the process) */
    if (!file_in_arena)
        kfree(file);
    if (f)
        vfs_close(f);
    if (r && p) {
        proc_detach(p);  /* the caller never learns about it */
        proc_kill(p, r); /* never ran: releases the arena */
        proc_put(p);
        p = nullptr;
    }
    if (err)
        *err = r;
    return p;
}
