#!/usr/bin/env python3
"""native-specs.py - the specs of the compiler on the board, made from toolchain/crtos.specs

    python3 native-specs.py crtos.specs nano.specs OUT

The board's GCC reads OUT as its own specs (/sd/crtos/usr/lib/gcc/arm-none-eabi/14.3.1/specs),
so "gcc x.c -o x.app" there follows the rules of arm-crtos-gcc on the PC. GCC takes no
%include or %rename in that file (only in files given with -specs=), so what crtos.specs gets
that way is written out here: a spec that crtos.specs builds on the built-in one (through
nano.specs' and its own %rename) becomes "+ ...", which GCC appends to the built-in spec.

What arm-crtos-gcc adds on its command line, the specs add here:
  - the CRTOS headers (/sd/crtos/usr/include) before newlib's;
  - the position-independent libraries (sysroot lib/xip) first for -mxip;
  - the CPU options need nothing: the board's GCC has one variant, built for the Cortex-M7.
And for the board's memory: GCC collects its garbage early (a small starting heap, a small
growth before the next collection), as it would on a machine with little memory; the
preprocessor is a pass of its own (-no-integrated-cpp: cc1 -E writes the preprocessed file,
a second cc1 compiles it without the macro tables and the headers' text - about 1.5 MB less
at the peak for C++ with library headers); C++ is C++14 (gnu++14) unless -std says otherwise
- the C++17 library headers need a few MB more.
"""
import re
import sys

INCLUDE = '/sd/crtos/usr/include'
GGC = '--param ggc-min-expand=30 --param ggc-min-heapsize=4096'
CXX_STD = '%{!std=*:%{!ansi:-std=gnu++14}}'
SEPARATE_CPP = '-no-integrated-cpp'


def parse(text):
    """{name: spec text} and the renames {new: old} of a specs file"""
    specs, renames = {}, {}
    name = None
    for line in text.split('\n'):
        if name is not None:
            specs[name] = line.strip()
            name = None
        elif line.startswith('%rename'):
            _, old, new = line.split()
            renames[new] = old
        elif re.match(r'^\*[A-Za-z_0-9]+:$', line):
            name = line[1:-1]
            specs[name] = ''
    return specs, renames


def rest_after(spec, ref):
    """@spec is "%(ref) rest": the rest"""
    if not spec.startswith('%(' + ref + ')'):
        raise SystemExit('native-specs: expected %%(%s) first in "%s"' % (ref, spec))
    return spec[len(ref) + 3:].strip()


def convert(crtos_text, nano_text):
    crtos, crtos_ren = parse(crtos_text)
    nano, nano_ren = parse(nano_text)
    if crtos_ren != {'crtos_base_link': 'link'} or nano_ren.get('nano_link') != 'link' or \
            nano_ren.get('nano_cpp_unique_options') != 'cpp_unique_options':
        raise SystemExit('native-specs: crtos.specs or nano.specs has changed (renames)')
    out = {}
    for name, spec in crtos.items():
        if name == 'cpp_unique_options':
            # crtos.specs: its own options, then nano's renamed built-in one
            own = spec.replace('%(nano_cpp_unique_options)', '').strip()
            out[name] = '+ -isystem %s %s' % (INCLUDE, own)
        elif name == 'self_spec':
            # every compilation with the preprocessor as a pass of its own
            out[name] = spec + ' ' + SEPARATE_CPP
        elif name == 'cc1plus':
            # C++14 unless asked otherwise: the C++17 library headers take more memory than
            # cc1plus has on the board (with a desktop running) for a program of a few headers
            out[name] = spec + ' ' + CXX_STD
        elif name == 'link':
            # crtos.specs: nano's link (the built-in one, then nano's library names), then its own
            out[name] = '+ %s %%{msingle-pic-base:-L%%R/lib/xip} %s' % (
                rest_after(nano['link'], 'nano_link'), rest_after(spec, 'crtos_base_link'))
        else:
            out[name] = spec
    for name, spec in out.items():
        if '%(nano_' in spec or '%(crtos_' in spec:
            raise SystemExit('native-specs: %s still refers to a renamed spec: %s' % (name, spec))
    out['cc1'] = '+ ' + GGC
    lines = ['# specs - how GCC on the CRTOS board builds programs: toolchain/crtos.specs (and the',
             '# parts of nano.specs it uses) with the board\'s paths, generated by',
             '# toolchain/native/native-specs.py. "+ " appends to the built-in spec.', '']
    for name, spec in out.items():
        lines += ['*%s:' % name, spec, '']
    return '\n'.join(lines)


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    texts = []
    for path in sys.argv[1:3]:
        with open(path, encoding='utf-8') as f:
            texts.append(f.read().replace('\r\n', '\n'))
    with open(sys.argv[3], 'w', encoding='utf-8', newline='\n') as f:
        f.write(convert(*texts))


if __name__ == '__main__':
    main()
