"""Convert a TrueType font into an Adafruit GFX font (1 bit per pixel), like fontconvert: a C
header, or a font file that libgfx loads at run time (gfx_font_load).

    python tools/fontconv.py FONT.ttf PIXELS NAME OUT.h [--first 32] [--last 126] [--preview P.png]
    python tools/fontconv.py FONT.ttf PIXELS NAME OUT.fnt

Glyphs are rendered by FreeType without anti-aliasing (hinted for the pixel grid), so small
sizes stay crisp. For monospaced fonts every glyph gets the same advance.

The font file (.fnt, little endian): "CRF1", first, last, line height (bytes), 0, the number
of glyphs (16 bits), 2 bytes 0, the size of the bitmaps (32 bits); then each glyph as 8 bytes
(bitmap offset 16 bits, width, height, x advance, x offset, y offset - signed -, 0) and the
bitmaps (every glyph starts on a byte, rows of bits from the most significant one).
"""
import argparse
import os
import struct

from PIL import Image, ImageDraw, ImageFont


def render(font, ch):
    """Bitmap of one glyph: (rows of 0/1, x offset, y offset from the baseline, advance)"""
    ascent, _ = font.getmetrics()
    left, top, right, bottom = font.getbbox(ch, mode='1')
    advance = int(round(font.getlength(ch, mode='1')))
    w, h = right - left, bottom - top
    if w <= 0 or h <= 0:
        return [], 0, 0, advance
    img = Image.new('1', (w, h), 0)
    ImageDraw.Draw(img).text((-left, -top), ch, font=font, fill=1)
    rows = [[1 if img.getpixel((x, y)) else 0 for x in range(w)] for y in range(h)]
    # trim empty borders
    while rows and not any(rows[0]):
        rows.pop(0)
        top += 1
    while rows and not any(rows[-1]):
        rows.pop()
    if not rows:
        return [], 0, 0, advance
    while all(not r[0] for r in rows):
        rows = [r[1:] for r in rows]
        left += 1
    while all(not r[-1] for r in rows):
        rows = [r[:-1] for r in rows]
    return rows, left, top - ascent, advance


def convert(ttf, pixels, first=32, last=126, line=None):
    """The glyphs of @ttf at @pixels: (glyphs, bits, bitmap bytes, line height, ascent, monospaced)"""
    font = ImageFont.truetype(ttf, pixels)
    ascent, descent = font.getmetrics()
    glyphs = []
    bits = []
    for code in range(first, last + 1):
        rows, xo, yo, adv = render(font, chr(code))
        glyphs.append((len(bits) // 8, len(rows[0]) if rows else 0, len(rows), adv, xo, yo, code))
        for r in rows:
            bits.extend(r)
        while len(bits) % 8:  # every glyph starts on a byte
            bits.append(0)
    mono = len({g[3] for g in glyphs}) == 1
    data = bytes(int(''.join(map(str, bits[i:i + 8])), 2) for i in range(0, len(bits), 8))
    return glyphs, bits, data, line or ascent + descent, ascent, mono


def write_fnt(path, glyphs, data, first, last, line):
    """The font file libgfx loads (see the top of this file)"""
    if len(data) > 0xFFFF:
        raise ValueError('%s: bitmaps over 64 KB' % path)
    out = bytearray(b'CRF1')
    out += struct.pack('<BBBBHHI', first, last, line, 0, len(glyphs), 0, len(data))
    for off, w, h, adv, xo, yo, _ in glyphs:
        out += struct.pack('<HBBBbbB', off, w, h, adv, xo, yo, 0)
    out += data
    with open(path, 'wb') as f:
        f.write(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('ttf')
    ap.add_argument('pixels', type=int)
    ap.add_argument('name')
    ap.add_argument('out')
    ap.add_argument('--first', type=int, default=32)
    ap.add_argument('--last', type=int, default=126)
    ap.add_argument('--line', type=int, help='line height (default: from the font)')
    ap.add_argument('--preview')
    ap.add_argument('--notice', help='copyright/licence line for the header')
    a = ap.parse_args()

    glyphs, bits, data, line, ascent, mono = convert(a.ttf, a.pixels, a.first, a.last, a.line)
    if a.out.endswith('.fnt'):
        write_fnt(a.out, glyphs, data, a.first, a.last, line)
        print('%s: %d glyphs, %d bytes of bitmaps, line %d' % (a.out, len(glyphs), len(data), line))
        return

    with open(a.out, 'w', newline='\n') as f:
        f.write('/* %s, %d px (%s), generated by tools/fontconv.py - do not edit */\n'
                % (os.path.basename(a.ttf), a.pixels, 'monospaced' if mono else 'proportional'))
        if a.notice:
            f.write('/* %s */\n' % a.notice)
        f.write('static const uint8_t %sBitmaps[] = {\n' % a.name)
        for i in range(0, len(data), 16):
            f.write('    ' + ', '.join('0x%02X' % b for b in data[i:i + 16]) + ',\n')
        f.write('};\n\nstatic const GFXglyph %sGlyphs[] = {\n' % a.name)
        for off, w, h, adv, xo, yo, code in glyphs:
            f.write('    { %5d, %2d, %2d, %2d, %3d, %3d }, /* 0x%02X %s */\n'
                    % (off, w, h, adv, xo, yo, code, repr(chr(code))))
        f.write('};\n\nconst GFXfont %s = { (uint8_t *)%sBitmaps, (GFXglyph *)%sGlyphs, 0x%02X, 0x%02X, %d };\n'
                % (a.name, a.name, a.name, a.first, a.last, line))
    print('%s: %d glyphs, %d bytes of bitmaps, line %d, advance %s' %
          (a.out, len(glyphs), len(data), line, glyphs[33][3] if mono else 'varies'))

    if a.preview:
        text = ['The quick brown fox jumps over the lazy dog 0123456789',
                'crtos:/sd/crtos$ ls -l /sd/crtos/apps | grep app > x.txt',
                '{}[]()<>!@#$%^&*_+-=|\\/;:\'",.?~` ABCDEFGHIJKLMNOPQRSTUVWXYZ']
        width = max(sum(glyphs[ord(ch) - a.first][3] for ch in s) for s in text)
        img = Image.new('RGB', (width + 8, line * len(text) + 8), (16, 16, 24))
        for row, s in enumerate(text):
            x, base = 4, 4 + row * line + ascent
            for ch in s:
                off, w, h, g_adv, xo, yo, code = glyphs[ord(ch) - a.first]
                for yy in range(h):
                    for xx in range(w):
                        k = off * 8 + yy * w + xx
                        if bits[k]:
                            img.putpixel((x + xo + xx, base + yo + yy), (220, 220, 220))
                x += g_adv
        img.resize((img.width * 2, img.height * 2), Image.NEAREST).save(a.preview)


if __name__ == '__main__':
    main()
