#!/usr/bin/env python3
"""Generate dts/include/imxrt1050-pinfunc.h from the SDK's drivers/fsl_iomuxc.h.

Each IOMUXC_<PAD>_<FUNCTION> SDK macro (muxRegister, muxMode, inputRegister,
inputDaisy, configRegister) becomes a space separated 5-cell DTS macro:
    #define MXRT1050_IOMUXC_GPIO_AD_B0_12_LPUART1_TX 0x401F80EC 0x2 0x0 0x0 0x401F82DC
used in pinctrl groups as  fsl,pins = <MXRT1050_IOMUXC_... CONFIG>;  where bit 30 of
CONFIG (IMX_PAD_SION) sets the pad's software input-on (SION) bit.
"""
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SRC = os.path.join(ROOT, 'drivers', 'fsl_iomuxc.h')
DST = os.path.join(ROOT, 'dts', 'include', 'imxrt1050-pinfunc.h')

DEF_RE = re.compile(r'^#define\s+(IOMUXC_(?:GPIO|SNVS)_\w+)\s+([^/\n]+)')


def main():
    out = ['/* Generated by tools/gen_pinfunc.py from drivers/fsl_iomuxc.h - do not edit */',
           '#ifndef IMXRT1050_PINFUNC_H', '#define IMXRT1050_PINFUNC_H', '',
           '#define IMX_PAD_SION 0x40000000', '']
    count = 0
    for line in open(SRC, encoding='utf-8'):
        m = DEF_RE.match(line)
        if not m:
            continue
        vals = [v.strip().rstrip('uU') for v in m.group(2).split(',')]
        if len(vals) != 5:
            continue
        vals = ['0x%X' % int(v, 0) for v in vals]
        out.append('#define MXRT1050_%s %s' % (m.group(1), ' '.join(vals)))
        count += 1
    out += ['', '#endif', '']
    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, 'w', newline='\n') as f:
        f.write('\n'.join(out))
    print('%s: %d pin functions' % (DST, count))


if __name__ == '__main__':
    main()
