#!/usr/bin/env python3
"""Generate what the NetSurf build needs before compiling (the job of NetSurf's own make
rules, which need a Unix host): tables of the libraries, the framebuffer front end's images
and font, the testament, the JavaScript DOM bindings (nsgenbind) and the resources that go to
the SD card.

    python tools/netsurf_prepare.py GEN_DIR SD_SHARE_DIR

Sources: third_party/netsurf (the browser) and third_party/netsurf-libs (its libraries). Generated files that
the libraries include by relative path are written into their source trees (as their own
make rules do); the rest goes to GEN_DIR. Everything is regenerated only when older than
its inputs. Host tools: perl, gperf and a host C compiler (gcc, e.g. MinGW) on the PATH or
in the usual places; images need Python's PIL.
"""
import glob
import os
import re
import shutil
import socket
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
NS = os.path.join(ROOT, 'third_party', 'netsurf')
LIBS = os.path.join(ROOT, 'third_party', 'netsurf-libs')

_WINGET = os.path.join(os.environ.get('LOCALAPPDATA', ''), 'Microsoft', 'WinGet')
# where the host tools are when they are not on the PATH (Git for Windows has perl; winget
# installs gperf and WinLibs' MinGW gcc into its package directory)
HOST_TOOL_PLACES = {
    'perl': [r'C:\Program Files\Git\usr\bin', r'C:\Strawberry\perl\bin'],
    'gperf': [os.path.join(_WINGET, 'Links'), os.path.join(_WINGET, 'Packages', 'oss-winget.gperf_*')],
    'gcc': [r'C:\mingw64\bin', r'C:\msys64\ucrt64\bin', r'C:\msys64\mingw64\bin',
            os.path.join(_WINGET, 'Packages', 'BrechtSanders.WinLibs.*', 'mingw64', 'bin')],
}


def find_host_tool(name):
    """A program for the build computer: on the PATH or where its installer puts it"""
    p = shutil.which(name)
    if p:
        return p
    exe = name + ('.exe' if os.name == 'nt' else '')
    for pattern in HOST_TOOL_PLACES.get(name, []):
        for d in sorted(glob.glob(pattern), reverse=True):
            if os.path.isfile(os.path.join(d, exe)):
                return os.path.join(d, exe)
    return None


def tool(name):
    p = find_host_tool(name)
    if not p:
        sys.exit('netsurf_prepare: %s not found ("crtos setup --netsurf" installs it)' % name)
    return p


PERL = None
GPERF = None
HOSTCC = None


def stale(out, *inputs):
    if not os.path.exists(out):
        return True
    t = os.path.getmtime(out)
    return any(os.path.getmtime(i) > t for i in inputs)


def run(cmd, cwd=None, env=None):
    r = subprocess.run(cmd, cwd=cwd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if r.returncode:
        sys.exit('netsurf_prepare: %s failed:\n%s' % (' '.join(cmd), r.stdout))
    return r.stdout


def write_if_changed(path, text):
    if os.path.exists(path) and open(path, encoding='utf-8', newline='').read() == text:
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


# ---- libraries ------------------------------------------------------------------------------

def libparserutils():
    lib = os.path.join(LIBS, 'libparserutils')
    out = os.path.join(lib, 'src', 'charset', 'aliases.inc')
    if stale(out, os.path.join(lib, 'build', 'Aliases'), os.path.join(lib, 'build', 'make-aliases.pl')):
        run([PERL, 'build/make-aliases.pl'], cwd=lib)


def libhubbub():
    lib = os.path.join(LIBS, 'libhubbub')
    out = os.path.join(lib, 'src', 'tokeniser', 'entities.inc')
    if stale(out, os.path.join(lib, 'build', 'Entities'), os.path.join(lib, 'build', 'make-entities.pl')):
        run([PERL, 'build/make-entities.pl'], cwd=lib)
    src = os.path.join(lib, 'src', 'treebuilder', 'element-type.gperf')
    out = os.path.join(lib, 'src', 'treebuilder', 'autogenerated-element-type.c')
    if stale(out, src):
        tmp = out + '.tmp'
        run([GPERF, '--output-file=' + tmp, src])
        text = open(tmp, encoding='utf-8').read()
        os.remove(tmp)
        text = re.sub(r'^(const struct element_type_map)', r'static \1', text, flags=re.M)
        write_if_changed(out, text)


def libsvgtiny():
    lib = os.path.join(LIBS, 'libsvgtiny')
    src = os.path.join(lib, 'src', 'colors.gperf')
    out = os.path.join(lib, 'src', 'autogenerated_colors.c')
    if stale(out, src):
        tmp = out + '.tmp'
        run([GPERF, '--output-file=' + tmp, src])
        text = open(tmp, encoding='utf-8').read()
        os.remove(tmp)
        text = re.sub(r'^(const struct svgtiny_named_color)', r'static \1', text, flags=re.M)
        write_if_changed(out, text)


def libpng(gen):
    """The build configuration libpng's make rules would generate: the prebuilt default"""
    src = os.path.join(LIBS, 'libpng', 'scripts', 'pnglibconf.h.prebuilt')
    out = os.path.join(gen, 'png', 'pnglibconf.h')
    if stale(out, src):
        os.makedirs(os.path.dirname(out), exist_ok=True)
        shutil.copyfile(src, out)


def libcss(build):
    lib = os.path.join(LIBS, 'libcss')
    pdir = os.path.join(lib, 'src', 'parse', 'properties')
    gen_c = os.path.join(pdir, 'css_property_parser_gen.c')
    spec = os.path.join(pdir, 'properties.gen')
    exe = os.path.join(build, 'css_property_parser_gen.exe')
    if stale(exe, gen_c):
        os.makedirs(build, exist_ok=True)
        run([HOSTCC, '-O1', '-o', exe, gen_c])
    for line in open(spec, encoding='utf-8'):
        m = re.match(r'^([^#][^:]+):', line)
        if not m:
            continue
        out = os.path.join(pdir, 'autogenerated_%s.c' % m.group(1))
        if stale(out, spec, exe):
            run([exe, '-o', out, line.rstrip('\r\n')])


# ---- the browser -----------------------------------------------------------------------------

def testament(gen):
    out = os.path.join(gen, 'testament.h')
    if not os.path.exists(out):
        os.makedirs(gen, exist_ok=True)
        # the host name comes from here: the script would run "hostname", and Windows' one
        # ends its line with CR LF - the CR would land inside a C string
        env = dict(os.environ, HOSTNAME=socket.gethostname())
        run([PERL, os.path.join(NS, 'tools', 'git-testament.pl'), NS.replace(os.sep, '/'), out.replace(os.sep, '/')],
            cwd=NS, env=env)
    # (also repairs a testament written before) no CR anywhere; Windows paths in C strings
    # with forward slashes, as a backslash starts an escape sequence
    with open(out, encoding='utf-8', errors='replace', newline='') as f:
        lines = f.read().replace('\r', '').split('\n')
    lines = [l.replace('\\', '/') if l.startswith('#define WT_ROOT') else l for l in lines]
    write_if_changed(out, '\n'.join(lines))


def c_bytes(data):
    rows = [', '.join('0x%02x' % b for b in data[i:i + 12]) for i in range(0, len(data), 12)]
    return ',\n  '.join(rows)


def js_array(src, out, name):
    """A script as a C array (xxd -i): @name[] and @name_len"""
    if not stale(out, src):
        return
    data = open(src, 'rb').read()
    write_if_changed(out, 'unsigned char %s[] = {\n  %s\n};\nunsigned int %s_len = %d;\n'
                     % (name, c_bytes(data), name, len(data)))


def js_arrays(srcs, out, name):
    """Scripts as C arrays and a table of them, @name[]: { name, source, length }, in order
    (dukky.c runs each by itself, so that one failing leaves the others running)"""
    if not stale(out, *srcs):
        return
    text = '/* %s - made by tools/netsurf_prepare.py */\n' % os.path.basename(out)
    table = []
    for i, src in enumerate(srcs):
        data = open(src, 'rb').read()
        label = '/'.join(os.path.normpath(src).split(os.sep)[-2:])
        text += 'static const unsigned char %s_%d[] = {\n  %s\n};\n' % (name, i, c_bytes(data))
        table.append('\t{ "%s", %s_%d, %d },' % (label, name, i, len(data)))
    text += ('static const struct {\n\tconst char *name;\n\tconst unsigned char *src;\n'
             '\tunsigned int len;\n} %s[] = {\n%s\n};\n' % (name, '\n'.join(table)))
    write_if_changed(out, text)


def javascript(gen, build):
    """JavaScript (Duktape): nsgenbind, built here with the host compiler (its parsers and
    lexers pregenerated in apps/netsurf/nsgenbind-gen: no bison or flex needed), makes the DOM
    bindings from the .bnd files and the Web IDL into GEN/duktape (sources.txt lists them for
    CMake); NetSurf's generics script and the scripts every page runs first (page_scripts)
    become C arrays there"""
    src = os.path.join(LIBS, 'nsgenbind', 'src')
    pre = os.path.join(ROOT, 'apps', 'netsurf', 'nsgenbind-gen')
    exe = os.path.join(build, 'nsgenbind.exe')
    sources = sorted(glob.glob(os.path.join(src, '*.c')) + glob.glob(os.path.join(pre, '*.c')))
    if stale(exe, *(sources + [os.path.join(pre, 'compat.h')])):
        os.makedirs(build, exist_ok=True)
        run([HOSTCC, '-O2', '-include', os.path.join(pre, 'compat.h'), '-I', src, '-I', pre, '-DYYENABLE_NLS=0',
             '-o', exe] + sources)
    js = os.path.join(NS, 'content', 'handlers', 'javascript')
    inputs = glob.glob(os.path.join(js, 'duktape', '*.bnd')) + glob.glob(os.path.join(js, 'WebIDL', '*.idl'))
    out = os.path.join(gen, 'duktape')
    mk = os.path.join(out, 'Makefile')
    if stale(mk, exe, *inputs):
        os.makedirs(out, exist_ok=True)
        # the sources include "<output directory>/binding.h": "duktape" below GEN, as dukky.c
        # includes it; nsgenbind finds the files a binding includes next to it by "/"
        run([exe, '-I', os.path.join(js, 'WebIDL').replace(os.sep, '/'),
             os.path.join(js, 'duktape', 'netsurf.bnd').replace(os.sep, '/'), 'duktape'], cwd=gen)
    m = re.search(r'^NSGENBIND_SOURCES:=(.*)$', open(mk, encoding='utf-8').read(), re.M)
    write_if_changed(os.path.join(out, 'sources.txt'), '\n'.join(m.group(1).split()) + '\n')
    js_array(os.path.join(js, 'duktape', 'generics.js'), os.path.join(out, 'generics.js.inc'), 'generics_js')
    js_arrays(page_scripts(), os.path.join(out, 'polyfill.js.inc'), 'polyfill_scripts')


def page_scripts():
    """What every page runs before its own scripts (polyfill.js.inc), in this order: NetSurf's
    polyfill.js, then CRTOS' prelude.js (what the library needs of the window), the polyfill
    library (ECMAScript up to 2017, URL, fetch: third_party/netsurf-libs/polyfill, MIT or
    Unlicense), newer.js (the later ECMAScript features) and dom.js (the parts of the DOM that
    NetSurf's bindings only declare)"""
    crtos = os.path.join(ROOT, 'apps', 'netsurf', 'js')
    if not os.path.exists(os.path.join(LIBS, 'polyfill', 'polyfill.js')):
        sys.exit("netsurf_prepare: third_party/netsurf-libs/polyfill is missing - 'crtos setup --netsurf' fetches it")
    return [os.path.join(NS, 'content', 'handlers', 'javascript', 'duktape', 'polyfill.js'),
            os.path.join(crtos, 'prelude.js'),
            os.path.join(LIBS, 'polyfill', 'polyfill.js'),
            os.path.join(crtos, 'newer.js'),
            os.path.join(crtos, 'dom.js')]


def libdom_headers(gen):
    """NetSurf and libsvgtiny include the libdom bindings as installed: dom/bindings/hubbub/...
    (the HTML parser) and dom/bindings/xml/... (the XML parser, on expat)"""
    for binding, names in (('hubbub', None), ('xml', ('xmlerror.h', 'xmlparser.h'))):
        src = os.path.join(LIBS, 'libdom', 'bindings', binding)
        dst = os.path.join(gen, 'include', 'dom', 'bindings', binding)
        os.makedirs(dst, exist_ok=True)
        for name in os.listdir(src):
            if name.endswith('.h') and (names is None or name in names) and \
                    stale(os.path.join(dst, name), os.path.join(src, name)):
                shutil.copyfile(os.path.join(src, name), os.path.join(dst, name))


def convert_image(src, out, name):
    """frontends/framebuffer/convert_image.c: RGBA pixels, cursors keep their hot spot marked
    with green pixels in the first row and column"""
    from PIL import Image
    img = Image.open(src).convert('RGBA')
    w, h = img.size
    px = img.load()
    cursor, hot_x, hot_y = True, 0, 0
    green = 0
    for i in range(w):
        r, g, b, a = px[i, 0]
        if a == 255:
            if g == 255:
                green += 1
                hot_x = i
            if b or r:
                cursor = False
                break
        elif a:
            cursor = False
            break
    if cursor and green != 1:
        cursor = False
    if cursor:
        for i in range(h):
            r, g, b, a = px[0, i]
            if a == 255:
                if g == 255:
                    green += 1
                    hot_y = i
                if b or r:
                    cursor = False
                    break
            elif a:
                cursor = False
                break
        if green != 2:
            cursor = False
    ox = oy = 1 if cursor else 0
    width, height = (w - 1, h - 1) if cursor else (w, h)
    rows = []
    for y in range(height):
        vals = []
        for x in range(width):
            vals.extend(px[x + ox, y + oy])
        rows.append('\t' + ''.join('0x%02x, ' % v for v in vals))
    text = ('/* This file is auto-generated from %s\n *\n * Do not edit this file directly.\n */\n\n'
            '#include <sys/types.h>\n\n#include <stdint.h>\n\n#include <stdbool.h>\n\n#include <libnsfb.h>\n\n'
            '#include "netsurf/plot_style.h"\n#include "framebuffer/gui.h"\n#include "framebuffer/fbtk.h"\n\n'
            'static uint8_t %s_pixdata[] = {\n%s\n};\n\n'
            'struct fbtk_bitmap %s = {\n\t.width\t\t= %d,\n\t.height\t\t= %d,\n\t.hot_x\t\t= %d,\n'
            '\t.hot_y\t\t= %d,\n\t.pixdata\t= %s_pixdata,\n};\n\n') % (
        os.path.basename(src), name, '\n'.join(rows), name, width, height,
        hot_x - 1 if cursor else 0, hot_y - 1 if cursor else 0, name)
    write_if_changed(out, text)


def fb_images(gen):
    makefile = open(os.path.join(NS, 'frontends', 'framebuffer', 'Makefile'), encoding='utf-8').read()
    res = os.path.join(NS, 'frontends', 'framebuffer', 'res')
    names = []
    for name, rel in re.findall(r'^FB_IMAGE_(\w+)\s*:=\s*(\S+)', makefile, flags=re.M):
        src = resolve(os.path.join(res, rel))
        out = os.path.join(gen, 'image-%s.c' % name)
        if stale(out, src, __file__):
            convert_image(src, out, name)
        names.append(name)
    return names


def fb_font(gen, build):
    src_c = os.path.join(NS, 'tools', 'convert_font.c')
    exe = os.path.join(build, 'convert_font.exe')
    if stale(exe, src_c):
        os.makedirs(build, exist_ok=True)
        run([HOSTCC, '-O1', '-o', exe, src_c])
    glyphs = os.path.join(NS, 'frontends', 'framebuffer', 'res', 'fonts', 'glyph_data')
    out_c = os.path.join(gen, 'font-ns-sans.c')
    out_h = os.path.join(gen, 'font-ns-sans.h')
    if stale(out_c, glyphs, exe) or stale(out_h, glyphs, exe):
        run([exe, '-H', out_h, glyphs, out_c])


def resolve(path, depth=0):
    """A git symlink checked out as a small file holding the target path"""
    if depth < 4 and os.path.getsize(path) < 200:
        target = open(path, 'rb').read().decode('latin-1').strip()
        if '\n' not in target and not target.startswith('<'):
            t = os.path.normpath(os.path.join(os.path.dirname(path), target))
            if os.path.isfile(t):
                return resolve(t, depth + 1)
    return path


def resources(share):
    res = os.path.join(NS, 'frontends', 'framebuffer', 'res')
    os.makedirs(share, exist_ok=True)
    for name in ('adblock.css', 'credits.html', 'default.css', 'internal.css', 'licence.html', 'netsurf.png',
                 'quirks.css', 'welcome.html', 'favicon.png'):
        src = resolve(os.path.join(res, name))
        dst = os.path.join(share, name)
        if stale(dst, src):
            shutil.copyfile(src, dst)
    msgs = os.path.join(share, 'Messages')
    fat = os.path.join(NS, 'resources', 'FatMessages')
    if stale(msgs, fat):
        run([PERL, os.path.join(NS, 'tools', 'split-messages.pl'), '-l', 'en', '-p', 'fb', '-f', 'messages',
             '-o', msgs, fat])


def main():
    global PERL, GPERF, HOSTCC
    gen = os.path.abspath(sys.argv[1])
    share = os.path.abspath(sys.argv[2])
    build = os.path.join(gen, 'host')
    PERL = tool('perl')
    GPERF = tool('gperf')
    HOSTCC = tool('gcc')
    libparserutils()
    libhubbub()
    libsvgtiny()
    libpng(gen)
    libcss(build)
    testament(gen)
    libdom_headers(gen)
    javascript(gen, build)
    names = fb_images(gen)
    fb_font(gen, build)
    resources(share)
    write_if_changed(os.path.join(gen, 'images.txt'), '\n'.join(names) + '\n')


if __name__ == '__main__':
    main()
